# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.5.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: andy.botting@ardc.edu.au
author_name: Andy Botting
has_ai_rules: false
has_binder: false
has_settings: false
kind: theme
labextension_name: nectar-jupyterlab-theme
project_short_description: ARDC Nectar JupyterLab theme
python_name: nectar_jupyterlab_theme
repository: https://github.com/NeCTAR-RC/nectar-jupyterlab-theme
test: false

